#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Sierpinski Triangle Generation Example
======================================

This example demonstrates how to generate Sierpinski triangles using fracDimPy.
The Sierpinski triangle is a classic two-dimensional fractal pattern, generated by
recursively removing the center part of triangles, with perfect self-similarity and
beautiful geometric structure.

Main Features:
- Generate Sierpinski triangles at different levels
- Visualize the step-by-step construction process of fractals
- Display theoretical fractal dimension and fill ratio

Theoretical Background:
- Fractal dimension of Sierpinski triangle: D = log(3)/log(2) ≈ 1.585
- Each iteration keeps 3 small triangles, removes the middle one
- As iteration increases, fill ratio gradually decreases toward 0
- Has perfect three-fold symmetry
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Sierpinski Triangle Generation Example")
    print("="*60)
    
    from fracDimPy import generate_sierpinski
    
    # Generate Sierpinski triangles
    print("\n1. Generating Sierpinski triangles...")
    levels = [3, 5, 7]  # Different iteration levels
    size = 512          # Image size
    
    fig, axes = plt.subplots(1, len(levels), figsize=(15, 5))
    
    for idx, level in enumerate(levels):
        triangle = generate_sierpinski(level=level, size=size)
        
        fill_ratio = np.sum(triangle) / (size * size) * 100
        print(f"   Level={level}: Image size {size}x{size}")
        print(f"   Fill ratio: {fill_ratio:.2f}%")
        
        # Display Sierpinski triangle
        axes[idx].imshow(triangle, cmap='binary', origin='upper')
        axes[idx].set_title(f'Sierpinski Triangle\n(Iteration Level={level})')
        axes[idx].axis('off')
        
        # Add theoretical fractal dimension annotation
        D_theoretical = np.log(3) / np.log(2)
        axes[idx].text(0.5, 0.02, 
                      f'Theoretical Fractal Dimension: D ≈ {D_theoretical:.3f}',
                      transform=axes[idx].transAxes,
                      ha='center',
                      bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_sierpinski.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
