#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Cantor Set Generation Example
==============================

This example demonstrates how to generate the classic Cantor set using fracDimPy.
The Cantor set is one of the earliest studied fractals, generated by recursively
removing the middle part of line segments, with self-similarity and discontinuity
everywhere.

Main Features:
- Generate Cantor sets at specified levels
- Visualize Cantor sets at multiple levels
- Save results as CSV files
- Display the step-by-step construction process of fractals

Theoretical Background:
- Fractal dimension of Cantor set: D = log(2)/log(3) ~= 0.6309
- Each iteration removes middle 1/3, keeps both ends 1/3 each
- The set formed after infinite iterations is uncountable
"""

import numpy as np
import os

import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Cantor Set Generation Example")
    print("="*60)
    
    from fracDimPy import generate_cantor_set
    
    # 1. Generate Cantor set
    print("\n1. Generating Cantor set...")
    level = 6  # Iteration level
    
    cantor = generate_cantor_set(level=level)
    
    print(f"   Iteration level: {level}")
    print(f"   Array length: {len(cantor)}")
    print(f"   Theoretical length: {3**level}")
    print(f"   Retained points: {np.sum(cantor)}")
    print(f"   Theoretical fractal dimension: {np.log(2)/np.log(3):.4f} (~= 0.6309)")
    
    # 2. Save as CSV file
    print("\n2. Saving Cantor set as CSV...")
    current_dir = os.path.dirname(os.path.abspath(__file__))
    csv_file = os.path.join(current_dir, f"cantor_set_level{level}.csv")
    np.savetxt(csv_file, cantor.astype(int), fmt='%d', delimiter=',', header='value', comments='')
    print(f"   File saved: {csv_file}")
    print(f"   Data description: Use 0 and 1 to indicate point existence, total {len(cantor)} points")
    
    # 3. Visualize Cantor set
    try:
        import matplotlib.pyplot as plt
        
        fig, axes = plt.subplots(2, 1, figsize=(12, 6))
        
        # Top plot: Display complete Cantor set (final level)
        axes[0].imshow([cantor], cmap='binary', aspect='auto')
        axes[0].set_title(f'Complete Cantor Set View (Iteration Level={level})')
        axes[0].set_yticks([])
        axes[0].set_xlabel('Position Index')
        
        # Bottom plot: Display step-by-step construction process of Cantor set
        axes[1].set_title('Cantor Set Construction Process (Level by Level)')
        for i in range(1, min(level+1, 7)):
            c = generate_cantor_set(level=i)
            y_pos = i * 1.2
            # Draw each retained line segment
            for j, val in enumerate(c):
                if val > 0:
                    axes[1].plot([j, j], [y_pos-0.3, y_pos+0.3], 'k-', linewidth=1)
            axes[1].text(-len(c)*0.05, y_pos, f'Level {i}', ha='right', va='center')
        
        axes[1].set_xlim(-len(c)*0.1, len(c)*1.1)
        axes[1].set_ylim(0, (level+1)*1.2 + 1)
        axes[1].set_xlabel('Position Index')
        axes[1].set_yticks([])
        axes[1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        output_file = os.path.join(current_dir, "result_cantor_set.png")
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"\n3. Visualization result saved: {output_file}")
        plt.show()
        
    except ImportError:
        print("\n3. Visualization failed: matplotlib library required")
    
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()

