#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Sierpinski Carpet Generation Example
=====================================

This example demonstrates how to generate Sierpinski carpets using fracDimPy.
The Sierpinski carpet is a two-dimensional generalization of the Sierpinski triangle,
and also a two-dimensional analog of the Menger sponge, generated by recursively
removing the center parts of square grids.

Main Features:
- Generate Sierpinski carpets at different levels
- Visualize the step-by-step construction process of fractals
- Display theoretical fractal dimension and fill ratio changes

Theoretical Background:
- Fractal dimension of Sierpinski carpet: D = log(8)/log(3) ≈ 1.8928
- Divide square into 9 equal parts, remove middle 1, keep surrounding 8
- Two-dimensional analog of Menger sponge
- Fill ratio decreases exponentially as iteration increases
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Sierpinski Carpet Generation Example")
    print("="*60)
    
    from fracDimPy import generate_sierpinski_carpet
    
    # Generate Sierpinski carpets
    print("\n1. Generating Sierpinski carpets...")
    levels = [3, 4, 5]  # Different iteration levels
    
    fig, axes = plt.subplots(1, len(levels), figsize=(15, 5))
    
    for idx, level in enumerate(levels):
        size = 3 ** level
        carpet = generate_sierpinski_carpet(level=level, size=size)
        
        total_pixels = size ** 2
        filled_pixels = np.sum(carpet)
        fill_ratio = filled_pixels / total_pixels * 100
        
        print(f"   Level={level}: Image size {size}x{size}")
        print(f"   Fill ratio: {fill_ratio:.2f}%")
        
        # Display Sierpinski carpet
        axes[idx].imshow(carpet, cmap='binary', origin='upper')
        axes[idx].set_title(f'Sierpinski Carpet\n(Iteration Level={level})')
        axes[idx].axis('off')
        
        # Add theoretical fractal dimension and fill ratio annotation
        D_theoretical = np.log(8) / np.log(3)
        axes[idx].text(0.5, -0.05, 
                      f'Theoretical Fractal Dimension: D ≈ {D_theoretical:.3f}\nFill Ratio: {fill_ratio:.1f}%',
                      transform=axes[idx].transAxes,
                      ha='center', va='top',
                      fontsize=9,
                      bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.7))
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_sierpinski_carpet.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\n" + "="*60)
    print("Theoretical Knowledge Supplement")
    print("="*60)
    print("   Sierpinski carpet is a two-dimensional analog of Menger sponge")
    print("   Each iteration divides square into 9 parts, removes center 1, keeps surrounding 8")
    print(f"   Fractal dimension: D = log(8)/log(3) ≈ {np.log(8)/np.log(3):.4f}")
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
