#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Test Takagi Surface Generation
==============================

Test cases for generating Takagi surfaces using fracDimPy.
The Takagi surface is a two-dimensional generalization of the Takagi curve,
a continuous but nowhere differentiable fractal surface generated by superimposing
waves of different scales, useful for simulating rough surfaces.

Theoretical Background:
- Fractal dimension of Takagi surface: D ∈ (2, 3)
- Larger D indicates rougher surfaces with greater fluctuations
- Formed by iteratively superimposing waves with different amplitudes and frequencies
- Parameter b controls surface fluctuation degree, b = 2^D / 8
"""

import numpy as np
import pytest


def test_takagi_surface_basic_generation():
    """Test basic Takagi surface generation functionality."""
    from fracDimPy import generate_takagi_surface

    # Test basic generation
    dimension = 2.5
    level = 10
    size = 128

    surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

    # Test basic properties
    assert surface.shape == (size, size), f"Expected shape {(size, size)}, got {surface.shape}"
    assert surface.dtype in [np.float64, np.float32], "Expected float array for surface values"
    assert np.all(np.isfinite(surface)), "All surface values should be finite"

    # Test Takagi surface properties
    assert surface.min() < surface.max(), "Should have variation in surface values"
    assert len(np.unique(surface)) > 10, "Should have sufficient variation in values"

    # Test parameter b calculation
    b = 2**dimension / 8
    assert 2 < dimension < 3, f"Fractal dimension {dimension} should be in (2, 3)"
    assert b > 0, f"Parameter b {b} should be positive"


def test_takagi_surface_different_dimensions():
    """Test Takagi surface generation with different fractal dimensions."""
    from fracDimPy import generate_takagi_surface

    dimensions = [2.1, 2.3, 2.5, 2.7, 2.9]
    level = 8
    size = 64

    std_devs = []
    for dimension in dimensions:
        surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

        # Test basic properties
        assert surface.shape == (size, size), f"Dimension {dimension}: Incorrect shape"
        assert np.all(np.isfinite(surface)), f"Dimension {dimension}: All values should be finite"

        std_dev = surface.std()
        std_devs.append(std_dev)

        # Test parameter b calculation
        b = 2**dimension / 8
        assert 2 < dimension < 3, f"Dimension {dimension}: Should be in (2, 3)"
        assert b > 0, f"Dimension {dimension}: Parameter b should be positive"

    # Test that standard deviation generally increases with fractal dimension
    # Allow for some variation, but check general trend
    for i in range(1, len(dimensions)):
        # Higher dimension should generally give higher standard deviation
        # But we allow for some tolerance
        assert (
            std_devs[i] > 0
        ), f"Dimension {dimensions[i]}: Should have positive standard deviation"


def test_takagi_surface_different_levels():
    """Test Takagi surface generation with different iteration levels."""
    from fracDimPy import generate_takagi_surface

    levels = [5, 8, 12, 15]
    dimension = 2.5
    size = 128

    std_devs = []
    for level in levels:
        surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

        # Test basic properties
        assert surface.shape == (size, size), f"Level {level}: Incorrect shape"
        assert np.all(np.isfinite(surface)), f"Level {level}: All values should be finite"

        std_dev = surface.std()
        std_devs.append(std_dev)

        # Test that surface has variation
        assert surface.min() < surface.max(), f"Level {level}: Should have variation"

    # Test that higher levels generally increase detail (not necessarily std dev)
    for std_dev in std_devs:
        assert std_dev > 0, "Should have positive standard deviation at all levels"


def test_takagi_surface_theoretical_properties():
    """Test theoretical properties of Takagi surface."""
    from fracDimPy import generate_takagi_surface

    # Test with specific parameters
    dimension = 2.5
    level = 12
    size = 256

    surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

    # Test dimension bounds
    assert 2.0 < dimension < 3.0, f"Fractal dimension {dimension} should be in (2, 3)"

    # Test parameter b relationship
    b = 2**dimension / 8
    expected_b = 2**2.5 / 8
    assert abs(b - expected_b) < 0.001, f"Parameter b {b} should match formula"

    # Test that surface has expected statistical properties
    mean_val = surface.mean()
    std_val = surface.std()

    # Takagi surfaces should have reasonable statistical properties
    assert std_val > 0, "Surface should have positive standard deviation"
    assert not np.isnan(mean_val), "Mean should not be NaN"
    assert not np.isnan(std_val), "Standard deviation should not be NaN"

    # Test theoretical dimension-b relationship
    # From theory: D = log(8*b) / log(2), so b = 2^D / 8
    calculated_D = np.log(8 * b) / np.log(2)
    assert (
        abs(calculated_D - dimension) < 0.001
    ), f"Calculated D {calculated_D} should match input {dimension}"


def test_takagi_surface_edge_cases():
    """Test edge cases for Takagi surface generation."""
    from fracDimPy import generate_takagi_surface

    # Test with small size
    size = 32
    surface_small = generate_takagi_surface(dimension=2.3, level=5, size=size)
    assert surface_small.shape == (size, size), "Small size should work"
    assert np.all(np.isfinite(surface_small)), "Small size surface should be finite"
    assert surface_small.std() > 0, "Small size surface should have variation"

    # Test with extreme dimensions
    for dimension in [2.01, 2.99]:
        b = 2**dimension / 8
        assert 0 < b, f"Extreme dimension {dimension}: Parameter b should be positive"

        surface = generate_takagi_surface(dimension=dimension, level=8, size=64)
        assert surface.shape == (64, 64), f"Dimension {dimension}: Incorrect shape"
        assert np.all(np.isfinite(surface)), f"Dimension {dimension}: All values should be finite"
        assert surface.std() > 0, f"Dimension {dimension}: Should have variation"

    # Test with low level
    level = 3
    surface_low_level = generate_takagi_surface(dimension=2.5, level=level, size=128)
    assert surface_low_level.shape == (128, 128), "Low level should work"
    assert np.all(np.isfinite(surface_low_level)), "Low level surface should be finite"
    assert surface_low_level.std() > 0, "Low level surface should have variation"


def test_takagi_surface_self_similarity():
    """Test self-similarity property of Takagi surface."""
    from fracDimPy import generate_takagi_surface

    dimension = 2.5
    level = 10
    size = 256

    surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

    # Test statistical self-similarity by comparing statistics at different scales
    # This is a simplified test - true self-similarity analysis would be more complex

    # Sample different regions of the surface
    region_size = size // 4
    regions = [
        surface[:region_size, :region_size],
        surface[region_size : 2 * region_size, region_size : 2 * region_size],
        surface[-region_size:, -region_size:],
        surface[:region_size, -region_size:],
        surface[-region_size:, :region_size],
    ]

    # Test that different regions have similar statistical properties
    std_devs = [region.std() for region in regions]
    mean_std = np.mean(std_devs)

    # All regions should have similar standard deviations (within tolerance)
    for i, std_dev in enumerate(std_devs):
        assert (
            abs(std_dev - mean_std) < 0.5 * mean_std
        ), f"Region {i}: Standard deviation {std_dev} should be close to mean {mean_std}"


def test_takagi_surface_parameter_b():
    """Test the parameter b calculation and its effects."""
    from fracDimPy import generate_takagi_surface

    dimensions = [2.1, 2.3, 2.5, 2.7, 2.9]
    level = 8
    size = 64

    for dimension in dimensions:
        # Calculate expected b
        expected_b = 2**dimension / 8

        # Generate surface
        surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

        # Test that surface was generated successfully
        assert surface.shape == (size, size), f"Dimension {dimension}: Incorrect shape"
        assert np.all(np.isfinite(surface)), f"Dimension {dimension}: All values should be finite"

        # Test b properties
        assert expected_b > 0, f"Dimension {dimension}: Expected b should be positive"

        # Test that higher dimensions give higher b values
        if dimension > 2.1:
            current_b = 2**dimension / 8
            reference_b = 2**2.1 / 8
            assert current_b > reference_b, f"Higher dimension {dimension} should give higher b"

        # Test theoretical relationship: D = log(8*b) / log(2)
        calculated_D = np.log(8 * expected_b) / np.log(2)
        assert (
            abs(calculated_D - dimension) < 0.001
        ), f"Dimension {dimension}: Calculated D {calculated_D} should match input"


def test_takagi_surface_deterministic_properties():
    """Test deterministic properties of Takagi surface."""
    from fracDimPy import generate_takagi_surface

    # Takagi surface is deterministic (unlike FBM)
    # The same parameters should produce the same result
    dimension = 2.5
    level = 10
    size = 128

    # Generate surface twice with same parameters
    surface1 = generate_takagi_surface(dimension=dimension, level=level, size=size)
    surface2 = generate_takagi_surface(dimension=dimension, level=level, size=size)

    # Test that both are valid
    assert surface1.shape == (size, size), "First surface should have correct shape"
    assert surface2.shape == (size, size), "Second surface should have correct shape"
    assert np.all(np.isfinite(surface1)), "First surface should be finite"
    assert np.all(np.isfinite(surface2)), "Second surface should be finite"

    # Test that both have variation
    assert surface1.std() > 0, "First surface should have variation"
    assert surface2.std() > 0, "Second surface should have variation"

    # Since Takagi surface is deterministic, results should be identical
    assert np.array_equal(surface1, surface2), "Takagi surface should be deterministic"

    # Test that surfaces have reasonable symmetry properties
    # Takagi surface should have some symmetry (simplified test)
    assert surface1.mean() is not None, "Surface should have a defined mean"


@pytest.mark.parametrize("dimension", [2.1, 2.3, 2.5, 2.7, 2.9])
def test_takagi_surface_dimension_parameter(dimension):
    """Test Takagi surface generation with different dimension parameters."""
    from fracDimPy import generate_takagi_surface

    level = 8
    size = 64
    surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

    assert surface.shape == (size, size), f"Dimension {dimension}: Correct shape"
    assert np.all(np.isfinite(surface)), f"Dimension {dimension}: All values should be finite"
    assert surface.std() > 0, f"Dimension {dimension}: Should have variation"

    # Test dimension bounds
    assert 2.0 < dimension < 3.0, f"Dimension {dimension}: Should be in valid range"

    # Test parameter b calculation
    b = 2**dimension / 8
    assert 0.0 < b, f"Dimension {dimension}: Parameter b should be positive"

    # Test theoretical relationship
    calculated_D = np.log(8 * b) / np.log(2)
    assert (
        abs(calculated_D - dimension) < 0.001
    ), f"Dimension {dimension}: Calculated D should match input"


@pytest.mark.parametrize("level", [5, 8, 12, 15])
def test_takagi_surface_level_parameter(level):
    """Test Takagi surface generation with different level parameters."""
    from fracDimPy import generate_takagi_surface

    dimension = 2.5
    size = 128
    surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

    assert surface.shape == (size, size), f"Level {level}: Correct shape"
    assert np.all(np.isfinite(surface)), f"Level {level}: All values should be finite"
    assert surface.std() > 0, f"Level {level}: Should have variation"
    assert surface.min() < surface.max(), f"Level {level}: Should have variation"

    # Test that level affects surface complexity
    # Higher levels should generally produce more detailed surfaces
    unique_values = len(np.unique(np.round(surface, 6)))
    assert unique_values > 10, f"Level {level}: Should have sufficient unique values"


@pytest.mark.parametrize("size", [32, 64, 128, 256])
def test_takagi_surface_size_parameter(size):
    """Test Takagi surface generation with different size parameters."""
    from fracDimPy import generate_takagi_surface

    dimension = 2.5
    level = 8
    surface = generate_takagi_surface(dimension=dimension, level=level, size=size)

    assert surface.shape == (size, size), f"Size {size}: Correct shape"
    assert np.all(np.isfinite(surface)), f"Size {size}: All values should be finite"
    assert surface.std() > 0, f"Size {size}: Should have variation"

    # Test that larger surfaces have more unique values
    unique_values = len(np.unique(np.round(surface, 6)))
    assert unique_values > size, f"Size {size}: Should have sufficient variation"
