#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Test Vicsek Fractal Generation
=============================

Test cases for generating Vicsek fractals using fracDimPy.
The Vicsek fractal, also known as "Vicsek fractal", is a cross-like fractal pattern
generated by recursively placing small squares at the center and four corners of a square.

Theoretical Background:
- Fractal dimension of Vicsek fractal: D = log(5)/log(3) ~= 1.465
- Divide square into 9 equal parts, keep center and four corners (5 parts total)
- Structure resembles cross or plus sign shape
- Related to Sierpinski carpet but with different retention pattern
"""

import numpy as np
import os
import pytest


def test_vicsek_fractal_basic_generation():
    """Test basic Vicsek fractal generation functionality."""
    from fracDimPy import generate_vicsek_fractal

    # Test basic generation
    level = 4

    fractal = generate_vicsek_fractal(level=level)

    # Test basic properties
    expected_size = 3**level
    assert fractal.shape == (expected_size, expected_size), f"Fractal should be {expected_size}x{expected_size}"
    assert fractal.dtype in [np.float64, np.float32, np.uint8, np.bool_], "Valid image dtype expected"
    assert np.all(np.isfinite(fractal)), "All values should be finite"

    # Test image properties
    assert np.any(fractal > 0), "Fractal should contain non-zero values"
    assert np.any(fractal < np.max(fractal)), "Should have variation in values"

    # Test that it's not completely filled or empty
    fill_ratio = np.sum(fractal > 0) / (expected_size * expected_size)
    assert 0.05 < fill_ratio < 0.9, "Fill ratio should be reasonable"


def test_vicsek_fractal_different_levels():
    """Test Vicsek fractal generation at different iteration levels."""
    from fracDimPy import generate_vicsek_fractal

    levels = [0, 1, 2, 3, 4]

    fill_ratios = []
    for level in levels:
        fractal = generate_vicsek_fractal(level=level)

        # Test basic properties
        expected_size = 3**level
        assert fractal.shape == (expected_size, expected_size), f"Level {level}: Incorrect image size"

        # Calculate fill ratio
        non_zero_pixels = np.sum(fractal > 0)
        fill_ratio = non_zero_pixels / (expected_size * expected_size)
        fill_ratios.append(fill_ratio)

        # Should have some non-zero pixels for all levels
        assert non_zero_pixels > 0, f"Level {level}: Should have non-zero pixels"

    # Test that fill ratio generally decreases with level (approximate)
    # Vicsek fractal should become sparser as level increases
    for i in range(1, len(levels)):
        # Allow some tolerance due to discretization effects
        assert fill_ratios[i] <= fill_ratios[i-1] * 1.1, \
            f"Fill ratio should generally decrease with level (level {i} vs {i-1})"


def test_vicsek_fractal_theoretical_properties():
    """Test theoretical properties of Vicsek fractal."""
    from fracDimPy import generate_vicsek_fractal

    # Test theoretical fractal dimension
    theoretical_dim = np.log(5) / np.log(3)
    assert 1.46 < theoretical_dim < 1.47, "Theoretical dimension should be ~1.465"

    # Test theoretical fill ratio: (5/9)^level for continuous case
    level = 4
    fractal = generate_vicsek_fractal(level=level)

    actual_fill_ratio = np.sum(fractal > 0) / (fractal.shape[0] * fractal.shape[1])
    theoretical_fill_ratio = (5/9) ** level

    # Allow tolerance due to discretization
    assert abs(actual_fill_ratio - theoretical_fill_ratio) < 0.1, \
        f"Actual fill ratio {actual_fill_ratio:.4f} should be close to theoretical {theoretical_fill_ratio:.4f}"


def test_vicsek_fractal_cross_structure():
    """Test cross-like structure property of Vicsek fractal."""
    from fracDimPy import generate_vicsek_fractal

    level = 3
    fractal = generate_vicsek_fractal(level=level)

    # Test self-similarity by checking that the pattern forms a cross structure
    # The Vicsek fractal should have 5-fold pattern (center and 4 corners)
    total_size = fractal.shape[0]
    sub_size = total_size // 3

    # Test that the center is filled (for level >= 1)
    if level >= 1:
        center_start = sub_size
        center_end = 2 * sub_size
        center_region = fractal[center_start:center_end, center_start:center_end]
        assert np.any(center_region > 0), "Center region should be filled"

    # Test that the 4 corner regions contain similar patterns
    positions = [
        (0, 0), (0, 2*sub_size),
        (2*sub_size, 0), (2*sub_size, 2*sub_size)
    ]

    sub_patterns = []
    for y, x in positions:
        sub_pattern = fractal[y:y+sub_size, x:x+sub_size]
        sub_patterns.append(np.sum(sub_pattern > 0))

    # All 4 corner sub-patterns should have similar fill ratios
    if len(sub_patterns) >= 2:
        mean_fill = np.mean(sub_patterns)
        for i, fill_count in enumerate(sub_patterns):
            assert abs(fill_count - mean_fill) < mean_fill * 0.5, \
                f"Corner pattern {i} should have similar fill count to mean"


def test_vicsek_fractal_symmetry():
    """Test symmetry properties of Vicsek fractal."""
    from fracDimPy import generate_vicsek_fractal

    level = 2
    fractal = generate_vicsek_fractal(level=level)

    # Test that the fractal has 4-fold rotational symmetry (approximately)
    # Check that it's not just a random pattern
    non_zero_coords = np.where(fractal > 0)

    if len(non_zero_coords[0]) > 0:
        # Get centroid
        centroid_y = np.mean(non_zero_coords[0])
        centroid_x = np.mean(non_zero_coords[1])

        # Should be roughly centered
        total_size = fractal.shape[0]
        assert abs(centroid_y - total_size // 2) < total_size // 4, "Should be roughly centered vertically"
        assert abs(centroid_x - total_size // 2) < total_size // 4, "Should be roughly centered horizontally"


def test_vicsek_fractal_edge_cases():
    """Test edge cases for Vicsek fractal generation."""
    from fracDimPy import generate_vicsek_fractal

    # Test with level 0 (should be a filled square)
    fractal_0 = generate_vicsek_fractal(level=0)
    expected_size = 3**0
    assert fractal_0.shape == (expected_size, expected_size), "Level 0 should have size 1x1"
    assert np.sum(fractal_0 > 0) > 0, "Level 0 should have non-zero pixels"

    # Test with level 1
    fractal_1 = generate_vicsek_fractal(level=1)
    expected_size = 3**1
    assert fractal_1.shape == (expected_size, expected_size), "Level 1 should have size 3x3"

    # Check that center and corners are filled for level 1, edges should be empty
    assert fractal_1[1, 1] > 0, "Level 1 center should be filled"
    assert fractal_1[0, 0] > 0, "Level 1 top-left corner should be filled"
    assert fractal_1[0, 2] > 0, "Level 1 top-right corner should be filled"
    assert fractal_1[2, 0] > 0, "Level 1 bottom-left corner should be filled"
    assert fractal_1[2, 2] > 0, "Level 1 bottom-right corner should be filled"

    # Edges should be empty
    assert fractal_1[0, 1] == 0, "Level 1 top edge should be empty"
    assert fractal_1[1, 0] == 0, "Level 1 left edge should be empty"
    assert fractal_1[1, 2] == 0, "Level 1 right edge should be empty"
    assert fractal_1[2, 1] == 0, "Level 1 bottom edge should be empty"


@pytest.mark.parametrize("level", [0, 1, 2, 3, 4])
def test_vicsek_fractal_level_parameter(level):
    """Test Vicsek fractal generation with different level parameters."""
    from fracDimPy import generate_vicsek_fractal

    fractal = generate_vicsek_fractal(level=level)

    expected_size = 3**level
    assert fractal.shape == (expected_size, expected_size), f"Level {level}: Correct image size"
    assert np.sum(fractal > 0) > 0, f"Level {level}: Should have non-zero pixels"
    assert np.all(np.isfinite(fractal)), f"Level {level}: All values should be finite"

    # Test that higher levels have appropriate fill ratios
    fill_ratio = np.sum(fractal > 0) / (expected_size * expected_size)
    assert 0.01 < fill_ratio < 1.0, f"Level {level}: Fill ratio should be reasonable"


def test_vicsek_fractal_fill_ratio_properties():
    """Test fill ratio properties across different levels."""
    from fracDimPy import generate_vicsek_fractal

    levels = [1, 2, 3, 4]

    fill_ratios = []
    for level in levels:
        fractal = generate_vicsek_fractal(level=level)
        fill_ratio = np.sum(fractal > 0) / (fractal.shape[0] * fractal.shape[1])
        fill_ratios.append(fill_ratio)

        # Should have decreasing fill ratio
        if level > 1:
            theoretical_ratio = (5/9) ** level
            # Allow tolerance for discretization
            assert abs(fill_ratio - theoretical_ratio) < 0.15, \
                f"Level {level}: Fill ratio should be close to theoretical (5/9)^level"

    # Test monotonic decrease
    for i in range(1, len(fill_ratios)):
        assert fill_ratios[i] <= fill_ratios[i-1], \
            f"Fill ratio should decrease with level (level {i} vs {i-1})"


def test_vicsek_vs_sierpinski_carpet():
    """Test that Vicsek fractal differs from Sierpinski carpet."""
    from fracDimPy import generate_vicsek_fractal, generate_sierpinski_carpet

    level = 2

    vicsek = generate_vicsek_fractal(level=level)
    carpet = generate_sierpinski_carpet(level=level)

    # Both should have same size
    assert vicsek.shape == carpet.shape, "Both should have same dimensions"

    # But different fill ratios (Vicsek should be sparser)
    vicsek_fill = np.sum(vicsek > 0) / (vicsek.shape[0] * vicsek.shape[1])
    carpet_fill = np.sum(carpet > 0) / (carpet.shape[0] * carpet.shape[1])

    assert vicsek_fill < carpet_fill, "Vicsek should be sparser than Sierpinski carpet"

    # Different patterns (should not be identical)
    assert not np.array_equal(vicsek, carpet), "Vicsek and Sierpinski carpet should be different"