#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Takagi Curve Generation Example
================================

This example demonstrates how to generate Takagi curves (also known as Blancmange curves)
using fracDimPy. The Takagi curve is a continuous but nowhere differentiable fractal
curve with self-affine properties, generated by superimposing triangular waves of
different scales.

Main Features:
- Generate Takagi curves with different fractal dimensions
- Visualize curve morphology changes
- Display the effect of fractal dimension on curve roughness

Theoretical Background:
- Fractal dimension of Takagi curve: D ∈ (1, 2)
- Larger D indicates rougher and more irregular curves
- Formed by iteratively superimposing triangular waves with different amplitudes and frequencies
- Defined on [0,1] interval with periodicity
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Takagi Curve Generation Example")
    print("="*60)
    
    from fracDimPy import generate_takagi_curve
    
    # Generate Takagi curves
    print("\n1. Generating Takagi curves...")
    dimensions = [1.2, 1.5, 1.8]  # Different fractal dimensions
    level = 10                     # Iteration level
    length = 2048                  # Number of sampling points
    
    fig, axes = plt.subplots(len(dimensions), 1, figsize=(12, 10))
    
    for idx, dimension in enumerate(dimensions):
        x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)
        
        print(f"   Fractal dimension D={dimension}: Generated {len(x)} sampling points")
        
        # Plot Takagi curve
        axes[idx].plot(x, y, linewidth=0.8, color='steelblue')
        axes[idx].set_title(f'Takagi Curve (Fractal Dimension D={dimension}, Iteration Level={level})')
        axes[idx].set_xlabel('X Coordinate')
        axes[idx].set_ylabel('Y Coordinate')
        axes[idx].grid(True, alpha=0.3)
        axes[idx].set_xlim(0, 1)
        
        # Add value range information
        axes[idx].text(0.02, 0.95, 
                      f'Fractal Dimension: D = {dimension}\nValue Range: [{y.min():.4f}, {y.max():.4f}]',
                      transform=axes[idx].transAxes,
                      verticalalignment='top',
                      bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.5))
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_takagi_curve.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
