#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Vicsek Fractal Generation Example
==================================

This example demonstrates how to generate Vicsek fractals using fracDimPy.
The Vicsek fractal, also known as "Vicsek fractal", is a cross-like fractal pattern
generated by recursively placing small squares at the center and four corners of a square.

Main Features:
- Generate Vicsek fractals at different levels
- Visualize the step-by-step construction process of fractals
- Display theoretical fractal dimension and fill ratio

Theoretical Background:
- Fractal dimension of Vicsek fractal: D = log(5)/log(3) ~= 1.465
- Divide square into 9 equal parts, keep center and four corners (5 parts total)
- Structure resembles cross or plus sign shape
- Related to Sierpinski carpet but with different retention pattern
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Vicsek Fractal Generation Example")
    print("="*60)
    
    from fracDimPy import generate_vicsek_fractal
    
    # Generate Vicsek fractals
    print("\n1. Generating Vicsek fractals...")
    levels = [2, 4, 6]  # Different iteration levels
    
    fig, axes = plt.subplots(1, len(levels), figsize=(15, 5))
    
    for idx, level in enumerate(levels):
        size = 3 ** level
        vicsek = generate_vicsek_fractal(level=level, size=size)
        
        total_pixels = size ** 2
        filled_pixels = np.sum(vicsek)
        fill_ratio = filled_pixels / total_pixels * 100
        
        print(f"   Level={level}: Image size {size}x{size}")
        print(f"   Fill ratio: {fill_ratio:.2f}%")
        
        # Display Vicsek fractal
        axes[idx].imshow(vicsek, cmap='binary', origin='upper')
        axes[idx].set_title(f'Vicsek Fractal\n(Iteration Level={level})')
        axes[idx].axis('off')
        
        # Add theoretical fractal dimension and fill ratio annotation
        D_theoretical = np.log(5) / np.log(3)
        axes[idx].text(0.5, -0.05, 
                      f'Theoretical Fractal Dimension: D ~= {D_theoretical:.4f}\nFill Ratio: {fill_ratio:.1f}%',
                      transform=axes[idx].transAxes,
                      ha='center', va='top',
                      fontsize=9,
                      bbox=dict(boxstyle='round', facecolor='cyan', alpha=0.7))
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_vicsek.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\n" + "="*60)
    print("Theoretical Knowledge Supplement")
    print("="*60)
    print("   Vicsek fractal presents cross or plus sign shape")
    print("   Divide square into 3×3 parts, keep center and four corners, 5 parts total")
    print(f"   Fractal dimension: D = log(5)/log(3) ~= {np.log(5)/np.log(3):.4f}")
    print("   Similar to Sierpinski carpet but with different retention pattern")
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
