#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Weierstrass-Mandelbrot (WM) Curve Generation Example
====================================================

This example demonstrates how to generate Weierstrass-Mandelbrot (WM) curves using fracDimPy.
The WM curve is a generalization of the Weierstrass function, a classic continuous but
nowhere differentiable fractal curve generated by superimposing infinitely many sine waves
with different frequencies and amplitudes.

Main Features:
- Generate WM curves with different fractal dimensions
- Visualize curve morphology changes
- Display the effect of fractal dimension on curve roughness

Theoretical Background:
- Fractal dimension of WM curve: D ∈ (1, 2)
- Larger D indicates rougher and more irregular curves
- Constructed in Fourier series form: superimpose sine waves of different frequencies
- Amplitude of each sine wave decays according to power law as frequency increases
- Deterministic fractal curve (different from randomness of FBM)
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Weierstrass-Mandelbrot Curve Generation Example")
    print("="*60)
    
    from fracDimPy import generate_wm_curve
    
    # Generate WM curves
    print("\n1. Generating Weierstrass-Mandelbrot curves...")
    dimensions = [1.2, 1.5, 1.8]  # Different fractal dimensions
    length = 2048                  # Number of sampling points
    
    fig, axes = plt.subplots(len(dimensions), 1, figsize=(12, 10))
    
    for idx, dimension in enumerate(dimensions):
        x, y = generate_wm_curve(dimension=dimension, length=length)
        
        print(f"   Fractal dimension D={dimension}: Generated {len(x)} sampling points")
        
        # Plot WM curve
        axes[idx].plot(x, y, linewidth=0.5, color='steelblue')
        axes[idx].set_title(f'Weierstrass-Mandelbrot Curve (Fractal Dimension D={dimension})')
        axes[idx].set_xlabel('X Coordinate')
        axes[idx].set_ylabel('Y Coordinate')
        axes[idx].grid(True, alpha=0.3)
        
        # Add value range information
        axes[idx].text(0.02, 0.95, 
                      f'Value Range: [{y.min():.3f}, {y.max():.3f}]',
                      transform=axes[idx].transAxes,
                      verticalalignment='top',
                      bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_wm_curve.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
