#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Menger Sponge Generation Example
=================================

This example demonstrates how to generate Menger sponges using fracDimPy.
The Menger sponge is a three-dimensional generalization of the Sierpinski carpet,
a classic three-dimensional fractal structure generated by recursively removing
the center parts from cubes, with infinite surface area and zero volume.

Main Features:
- Generate Menger sponges at different levels
- Visualize fractal structure in 3D voxel form
- Statistics on volume fill ratio changes
- Display theoretical fractal dimension

Theoretical Background:
- Fractal dimension of Menger sponge: D = log(20)/log(3) ≈ 2.727
- Divide cube into 27 equal parts (3×3×3), remove center and face centers (7 total), keep 20
- As iteration increases, volume tends to 0, surface area tends to infinity
- Three-dimensional analog of Sierpinski carpet
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Menger Sponge Generation Example")
    print("="*60)
    
    from fracDimPy import generate_menger_sponge
    
    # Generate Menger sponges
    print("\n1. Generating Menger sponges...")
    levels = [1, 2, 3]  # Different iteration levels
    
    fig = plt.figure(figsize=(15, 5))
    
    for idx, level in enumerate(levels):
        size = 3 ** level
        sponge = generate_menger_sponge(level=level, size=size)
        
        total_voxels = size ** 3
        filled_voxels = np.sum(sponge)
        fill_ratio = filled_voxels / total_voxels * 100
        
        print(f"   Level={level}: Grid size {size}x{size}x{size}")
        print(f"   Filled voxels: {filled_voxels}/{total_voxels} ({fill_ratio:.2f}%)")
        
        # 3D visualization of Menger sponge
        try:
            from mpl_toolkits.mplot3d import Axes3D
            
            ax = fig.add_subplot(1, len(levels), idx+1, projection='3d')
            
            # Create color array
            colors = np.empty(sponge.shape, dtype=object)
            colors[sponge == 1] = 'cyan'
            
            # Use voxels function to plot 3D voxels
            ax.voxels(sponge, facecolors=colors, edgecolors='gray', 
                     linewidth=0.1, alpha=0.9)
            
            ax.set_title(f'Menger Sponge\n(Iteration Level={level})')
            ax.set_xlabel('X Axis')
            ax.set_ylabel('Y Axis')
            ax.set_zlabel('Z Axis')
            
            # Set equal aspect ratio for axes
            ax.set_box_aspect([1,1,1])
            
        except ImportError:
            print("   Warning: mpl_toolkits.mplot3d required for 3D visualization")
    
    # Add theoretical description
    D_theoretical = np.log(20) / np.log(3)
    fig.text(0.5, 0.02, 
            f'Theoretical Fractal Dimension: D = log(20)/log(3) ≈ {D_theoretical:.3f}',
            ha='center', fontsize=12,
            bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))
    
    plt.tight_layout(rect=[0, 0.05, 1, 1])
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_menger_sponge.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\n" + "="*60)
    print("Theoretical Knowledge Supplement")
    print("="*60)
    print("   Menger sponge is a three-dimensional generalization of Sierpinski carpet")
    print("   It is the three-dimensional analog of Sierpinski triangle (2D) and Cantor set (1D)")
    print(f"   Fractal dimension: D = log(20)/log(3) ≈ {D_theoretical:.4f}")
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
