#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Test Menger Sponge Generation
==============================

Test cases for generating Menger sponges using fracDimPy.
The Menger sponge is a three-dimensional generalization of the Sierpinski carpet,
a classic three-dimensional fractal structure generated by recursively removing
the center parts from cubes, with infinite surface area and zero volume.

Theoretical Background:
- Fractal dimension of Menger sponge: D = log(20)/log(3) ~= 2.727
- Divide cube into 27 equal parts (3×3×3), remove center and face centers (7 total), keep 20
- As iteration increases, volume tends to 0, surface area tends to infinity
- Three-dimensional analog of Sierpinski carpet
"""

import numpy as np
import pytest


def test_menger_sponge_basic_generation():
    """Test basic Menger sponge generation functionality."""
    from fracDimPy import generate_menger_sponge

    # Test basic generation
    level = 2
    size = 3 ** level
    sponge = generate_menger_sponge(level=level, size=size)

    # Test basic properties
    assert sponge.shape == (size, size, size), f"Expected shape {(size, size, size)}, got {sponge.shape}"
    assert sponge.dtype in [np.float64, np.float32, np.uint8, np.bool_], "Expected valid dtype"
    assert np.all(np.isfinite(sponge)), "All values should be finite"

    # Test Menger sponge properties
    assert np.any(sponge > 0), "Should have some filled voxels"
    assert np.sum(sponge) < size ** 3, "Should not fill all voxels"

    # Test boundary conditions
    assert sponge[0, 0, 0] > 0, "Corner voxels should be filled"
    assert sponge[0, 0, -1] > 0, "Corner voxels should be filled"
    assert sponge[0, -1, 0] > 0, "Corner voxels should be filled"
    assert sponge[-1, 0, 0] > 0, "Corner voxels should be filled"


def test_menger_sponge_different_levels():
    """Test Menger sponge generation at different iteration levels."""
    from fracDimPy import generate_menger_sponge

    levels = [0, 1, 2, 3]

    for level in levels:
        size = 3 ** level
        sponge = generate_menger_sponge(level=level, size=size)

        # Test shape property
        assert sponge.shape == (size, size, size), f"Level {level}: Expected shape {(size, size, size)}, got {sponge.shape}"

        filled_voxels = np.sum(sponge)
        total_voxels = size ** 3
        fill_ratio = filled_voxels / total_voxels

        # Test valid fill ratio
        assert 0 <= fill_ratio <= 1, f"Level {level}: Invalid fill ratio {fill_ratio}"

        # For level > 0, should have fewer filled voxels than total
        if level > 0:
            assert fill_ratio < 1.0, f"Level {level}: Should not fill all voxels"
            assert fill_ratio > 0.0, f"Level {level}: Should have some filled voxels"


def test_menger_sponge_theoretical_properties():
    """Test theoretical properties of Menger sponge."""
    from fracDimPy import generate_menger_sponge

    # Test with higher level for better approximation
    level = 3
    size = 3 ** level
    sponge = generate_menger_sponge(level=level, size=size)

    filled_voxels = np.sum(sponge)
    total_voxels = size ** 3
    fill_ratio = filled_voxels / total_voxels

    # Theoretical fill ratio should be (20/27)^level
    theoretical_ratio = (20/27) ** level

    # Allow some tolerance for numerical precision
    assert abs(fill_ratio - theoretical_ratio) < 0.01, \
        f"Fill ratio {fill_ratio:.6f} should be close to theoretical {theoretical_ratio:.6f}"

    # Test theoretical fractal dimension
    theoretical_dim = np.log(20) / np.log(3)
    assert 2.72 < theoretical_dim < 2.73, "Theoretical dimension should be ~2.727"

    # Test that the center cube is empty for level >= 1
    if level >= 1:
        center_start = size // 3
        center_end = 2 * size // 3
        assert np.all(sponge[center_start:center_end, center_start:center_end, center_start:center_end] == 0), \
            "Center cube should be empty"


def test_menger_sponge_self_similarity():
    """Test self-similarity property of Menger sponge."""
    from fracDimPy import generate_menger_sponge

    level = 2
    size = 3 ** level
    sponge = generate_menger_sponge(level=level, size=size)

    # Test self-similarity: each of the 20 sub-cubes should contain
    # scaled copies of the level-1 Menger sponge
    sub_size = size // 3

    # Test that corner sub-cubes are identical (self-similarity)
    corner1 = sponge[:sub_size, :sub_size, :sub_size]
    corner2 = sponge[-sub_size:, :sub_size, :sub_size]
    corner3 = sponge[:sub_size, -sub_size:, :sub_size]
    corner4 = sponge[:sub_size, :sub_size, -sub_size]
    corner5 = sponge[-sub_size:, -sub_size:, :sub_size]
    corner6 = sponge[-sub_size:, :sub_size, -sub_size]
    corner7 = sponge[:sub_size, -sub_size:, -sub_size]
    corner8 = sponge[-sub_size:, -sub_size:, -sub_size:]

    # All 8 corners should be identical (filled completely at this level)
    assert np.array_equal(corner1, corner2), "Corner sub-cubes should be identical"
    assert np.array_equal(corner1, corner3), "Corner sub-cubes should be identical"
    assert np.array_equal(corner1, corner4), "Corner sub-cubes should be identical"
    assert np.array_equal(corner1, corner5), "Corner sub-cubes should be identical"
    assert np.array_equal(corner1, corner6), "Corner sub-cubes should be identical"
    assert np.array_equal(corner1, corner7), "Corner sub-cubes should be identical"
    assert np.array_equal(corner1, corner8), "Corner sub-cubes should be identical"

    # All corners should be completely filled
    assert np.all(corner1 > 0), "Corner sub-cubes should be completely filled"


def test_menger_sponge_edge_cases():
    """Test edge cases for Menger sponge generation."""
    from fracDimPy import generate_menger_sponge

    # Test level 0 (should be a single filled cube)
    sponge_0 = generate_menger_sponge(level=0, size=1)
    assert sponge_0.shape == (1, 1, 1), "Level 0 should be 1x1x1"
    assert sponge_0[0, 0, 0] > 0, "Level 0 should fill the single voxel"

    # Test with different levels to ensure robustness
    for level in [1, 2, 3]:
        size = 3 ** level
        sponge = generate_menger_sponge(level=level, size=size)
        assert sponge.shape == (size, size, size), f"Level {level}: Incorrect shape"
        assert np.sum(sponge) > 0, f"Level {level}: Should have filled voxels"
        assert np.sum(sponge) < size ** 3, f"Level {level}: Should not fill all voxels"


@pytest.mark.parametrize("level", [0, 1, 2, 3])
def test_menger_sponge_level_parameter(level):
    """Test Menger sponge generation with different level parameters."""
    from fracDimPy import generate_menger_sponge

    size = 3 ** level
    sponge = generate_menger_sponge(level=level, size=size)

    assert sponge.shape == (size, size, size), f"Level {level}: Correct shape"
    assert np.sum(sponge) > 0, f"Level {level}: Should have filled voxels"
    assert np.all(np.isfinite(sponge)), f"Level {level}: All values should be finite"

    # Test volume ratio decreases with level
    total_voxels = size ** 3
    filled_voxels = np.sum(sponge)
    fill_ratio = filled_voxels / total_voxels

    # For level >= 1, fill ratio should be (20/27)^level approximately
    if level >= 1:
        expected_ratio = (20/27) ** level
        assert abs(fill_ratio - expected_ratio) < 0.1, \
            f"Level {level}: Fill ratio {fill_ratio:.3f} should be close to {expected_ratio:.3f}"