#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Test Takagi Curve Generation
============================

Test cases for generating Takagi curves (also known as Blancmange curves) using fracDimPy.
The Takagi curve is a continuous but nowhere differentiable fractal curve with self-affine
properties, generated by superimposing triangular waves of different scales.

Theoretical Background:
- Fractal dimension of Takagi curve: D ∈ (1, 2)
- Larger D indicates rougher and more irregular curves
- Formed by iteratively superimposing triangular waves with different amplitudes and frequencies
- Defined on [0,1] interval with periodicity
"""

import numpy as np
import pytest


def test_takagi_curve_basic_generation():
    """Test basic Takagi curve generation functionality."""
    from fracDimPy import generate_takagi_curve

    # Test basic generation
    dimension = 1.5
    level = 10
    length = 1024

    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    # Test basic properties
    assert len(x) == length, f"Expected x length {length}, got {len(x)}"
    assert len(y) == length, f"Expected y length {length}, got {len(y)}"
    assert x.dtype in [np.float64, np.float32], "Expected float array for x coordinates"
    assert y.dtype in [np.float64, np.float32], "Expected float array for y coordinates"
    assert np.all(np.isfinite(x)), "All x values should be finite"
    assert np.all(np.isfinite(y)), "All y values should be finite"

    # Test Takagi curve properties
    assert y.min() < y.max(), "Should have variation in y values"
    assert len(np.unique(y)) > 10, "Should have sufficient variation in values"

    # Test dimension bounds
    assert 1 < dimension < 2, f"Fractal dimension {dimension} should be in (1, 2)"

    # Test x coordinate range (should be in [0, 1])
    assert x.min() >= 0, "X coordinates should be >= 0"
    assert x.max() <= 1.001, f"X coordinates should be <= 1, got {x.max()}"


def test_takagi_curve_different_dimensions():
    """Test Takagi curve generation with different fractal dimensions."""
    from fracDimPy import generate_takagi_curve

    dimensions = [1.1, 1.3, 1.5, 1.7, 1.9]
    level = 8
    length = 512

    std_devs = []
    for dimension in dimensions:
        x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

        # Test basic properties
        assert len(x) == length, f"Dimension {dimension}: Incorrect x length"
        assert len(y) == length, f"Dimension {dimension}: Incorrect y length"
        assert np.all(np.isfinite(x)), f"Dimension {dimension}: All x values should be finite"
        assert np.all(np.isfinite(y)), f"Dimension {dimension}: All y values should be finite"

        std_dev = y.std()
        std_devs.append(std_dev)

        # Test dimension bounds
        assert 1 < dimension < 2, f"Dimension {dimension}: Should be in (1, 2)"

        # Test x coordinate range
        assert x.min() >= 0, f"Dimension {dimension}: X coordinates should be >= 0"
        assert x.max() <= 1.001, f"Dimension {dimension}: X coordinates should be <= 1"

    # Test that standard deviation generally increases with fractal dimension
    for i in range(1, len(dimensions)):
        # Higher dimension should generally give higher standard deviation
        assert (
            std_devs[i] > 0
        ), f"Dimension {dimensions[i]}: Should have positive standard deviation"


def test_takagi_curve_different_levels():
    """Test Takagi curve generation with different iteration levels."""
    from fracDimPy import generate_takagi_curve

    levels = [5, 8, 12, 15]
    dimension = 1.5
    length = 1024

    std_devs = []
    for level in levels:
        x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

        # Test basic properties
        assert len(x) == length, f"Level {level}: Incorrect x length"
        assert len(y) == length, f"Level {level}: Incorrect y length"
        assert np.all(np.isfinite(x)), f"Level {level}: All x values should be finite"
        assert np.all(np.isfinite(y)), f"Level {level}: All y values should be finite"

        std_dev = y.std()
        std_devs.append(std_dev)

        # Test that curve has variation
        assert y.min() < y.max(), f"Level {level}: Should have variation"

    # Test that higher levels generally increase detail
    for std_dev in std_devs:
        assert std_dev > 0, "Should have positive standard deviation at all levels"


def test_takagi_curve_theoretical_properties():
    """Test theoretical properties of Takagi curve."""
    from fracDimPy import generate_takagi_curve

    # Test with specific parameters
    dimension = 1.5
    level = 12
    length = 2048

    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    # Test dimension bounds
    assert 1.0 < dimension < 2.0, f"Fractal dimension {dimension} should be in (1, 2)"

    # Test that curve has expected statistical properties
    mean_val = y.mean()
    std_val = y.std()

    # Takagi curves should have reasonable statistical properties
    assert std_val > 0, "Curve should have positive standard deviation"
    assert not np.isnan(mean_val), "Mean should not be NaN"
    assert not np.isnan(std_val), "Standard deviation should not be NaN"

    # Test x coordinate properties
    assert np.abs(x[0]) < 0.001, "First x coordinate should be close to 0"
    assert np.abs(x[-1] - 1.0) < 0.001, "Last x coordinate should be close to 1"

    # Test that x coordinates are monotonically increasing
    x_diffs = np.diff(x)
    assert np.all(x_diffs >= 0), "X coordinates should be monotonically increasing"


def test_takagi_curve_edge_cases():
    """Test edge cases for Takagi curve generation."""
    from fracDimPy import generate_takagi_curve

    # Test with small length
    length = 256
    x_small, y_small = generate_takagi_curve(dimension=1.3, level=5, length=length)
    assert len(x_small) == length, "Small length should work"
    assert len(y_small) == length, "Small length should work"
    assert np.all(np.isfinite(x_small)), "Small length x should be finite"
    assert np.all(np.isfinite(y_small)), "Small length y should be finite"
    assert y_small.std() > 0, "Small length curve should have variation"

    # Test with extreme dimensions
    for dimension in [1.01, 1.99]:
        x, y = generate_takagi_curve(dimension=dimension, level=8, length=512)
        assert len(x) == 512, f"Dimension {dimension}: Incorrect x length"
        assert len(y) == 512, f"Dimension {dimension}: Incorrect y length"
        assert np.all(np.isfinite(x)), f"Dimension {dimension}: All x values should be finite"
        assert np.all(np.isfinite(y)), f"Dimension {dimension}: All y values should be finite"
        assert y.std() > 0, f"Dimension {dimension}: Should have variation"

    # Test with low level
    level = 3
    x_low, y_low = generate_takagi_curve(dimension=1.5, level=level, length=1024)
    assert len(x_low) == 1024, "Low level should work"
    assert len(y_low) == 1024, "Low level should work"
    assert np.all(np.isfinite(x_low)), "Low level x should be finite"
    assert np.all(np.isfinite(y_low)), "Low level y should be finite"
    assert y_low.std() > 0, "Low level curve should have variation"


def test_takagi_curve_self_affinity():
    """Test self-affine properties of Takagi curve."""
    from fracDimPy import generate_takagi_curve

    dimension = 1.5
    level = 10
    length = 1024

    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    # Test statistical self-affinity by comparing statistics at different scales
    # This is a simplified test - true self-affinity analysis would be more complex

    # Sample different segments of the curve
    segment_size = length // 4
    segments = [
        (x[:segment_size], y[:segment_size]),
        (x[segment_size : 2 * segment_size], y[segment_size : 2 * segment_size]),
        (x[-segment_size:], y[-segment_size:]),
        (x[:segment_size], y[:segment_size]),  # Duplicate for comparison
    ]

    # Test that different segments have similar statistical properties (scaled)
    std_devs = [seg_y.std() for seg_x, seg_y in segments]
    mean_std = np.mean(std_devs[:3])  # Mean of first three unique segments

    # Segments should have similar standard deviations (within tolerance due to scaling)
    for i, std_dev in enumerate(std_devs[:3]):  # Skip the duplicate
        assert (
            abs(std_dev - mean_std) < 0.5 * mean_std
        ), f"Segment {i}: Standard deviation {std_dev} should be close to mean {mean_std}"


def test_takagi_curve_deterministic_properties():
    """Test deterministic properties of Takagi curve."""
    from fracDimPy import generate_takagi_curve

    # Takagi curve is deterministic (unlike FBM)
    # The same parameters should produce the same result
    dimension = 1.5
    level = 10
    length = 1024

    # Generate curve twice with same parameters
    x1, y1 = generate_takagi_curve(dimension=dimension, level=level, length=length)
    x2, y2 = generate_takagi_curve(dimension=dimension, level=level, length=length)

    # Test that both are valid
    assert len(x1) == length, "First curve should have correct x length"
    assert len(y1) == length, "First curve should have correct y length"
    assert len(x2) == length, "Second curve should have correct x length"
    assert len(y2) == length, "Second curve should have correct y length"

    # Test that both have variation
    assert y1.std() > 0, "First curve should have variation"
    assert y2.std() > 0, "Second curve should have variation"

    # Since Takagi curve is deterministic, results should be identical
    assert np.array_equal(x1, x2), "X coordinates should be identical"
    assert np.array_equal(y1, y2), "Y coordinates should be identical"


def test_takagi_curve_x_coordinates():
    """Test properties of x coordinates in Takagi curve."""
    from fracDimPy import generate_takagi_curve

    dimension = 1.5
    level = 8
    length = 1024

    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    # Test that x coordinates are in [0, 1]
    assert x.min() >= 0, "X coordinates should be >= 0"
    assert x.max() <= 1.001, f"X coordinates should be <= 1, got {x.max()}"

    # Test that first and last points are close to boundaries
    assert np.abs(x[0]) < 0.01, "First x coordinate should be close to 0"
    assert np.abs(x[-1] - 1.0) < 0.01, "Last x coordinate should be close to 1"

    # Test monotonicity
    x_diffs = np.diff(x)
    assert np.all(x_diffs >= -1e-10), "X coordinates should be monotonically increasing"

    # Test that x coordinates are roughly evenly spaced
    expected_spacing = 1.0 / (length - 1)
    actual_spacing = np.mean(x_diffs[x_diffs > 1e-10])  # Mean of positive differences
    assert (
        np.abs(actual_spacing - expected_spacing) < 0.1 * expected_spacing
    ), f"X spacing {actual_spacing} should be close to expected {expected_spacing}"


@pytest.mark.parametrize("dimension", [1.1, 1.3, 1.5, 1.7, 1.9])
def test_takagi_curve_dimension_parameter(dimension):
    """Test Takagi curve generation with different dimension parameters."""
    from fracDimPy import generate_takagi_curve

    level = 8
    length = 512
    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    assert len(x) == length, f"Dimension {dimension}: Correct x length"
    assert len(y) == length, f"Dimension {dimension}: Correct y length"
    assert np.all(np.isfinite(x)), f"Dimension {dimension}: All x values should be finite"
    assert np.all(np.isfinite(y)), f"Dimension {dimension}: All y values should be finite"
    assert y.std() > 0, f"Dimension {dimension}: Should have variation"

    # Test dimension bounds
    assert 1.0 < dimension < 2.0, f"Dimension {dimension}: Should be in valid range"

    # Test x coordinate properties
    assert x.min() >= 0, f"Dimension {dimension}: X coordinates should be >= 0"
    assert x.max() <= 1.001, f"Dimension {dimension}: X coordinates should be <= 1"


@pytest.mark.parametrize("level", [5, 8, 12, 15])
def test_takagi_curve_level_parameter(level):
    """Test Takagi curve generation with different level parameters."""
    from fracDimPy import generate_takagi_curve

    dimension = 1.5
    length = 1024
    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    assert len(x) == length, f"Level {level}: Correct x length"
    assert len(y) == length, f"Level {level}: Correct y length"
    assert np.all(np.isfinite(x)), f"Level {level}: All x values should be finite"
    assert np.all(np.isfinite(y)), f"Level {level}: All y values should be finite"
    assert y.std() > 0, f"Level {level}: Should have variation"
    assert y.min() < y.max(), f"Level {level}: Should have variation"

    # Test that level affects curve complexity
    unique_values = len(np.unique(np.round(y, 6)))
    assert unique_values > 10, f"Level {level}: Should have sufficient unique values"


@pytest.mark.parametrize("length", [256, 512, 1024, 2048])
def test_takagi_curve_length_parameter(length):
    """Test Takagi curve generation with different length parameters."""
    from fracDimPy import generate_takagi_curve

    dimension = 1.5
    level = 10
    x, y = generate_takagi_curve(dimension=dimension, level=level, length=length)

    assert len(x) == length, f"Length {length}: Correct x length"
    assert len(y) == length, f"Length {length}: Correct y length"
    assert np.all(np.isfinite(x)), f"Length {length}: All x values should be finite"
    assert np.all(np.isfinite(y)), f"Length {length}: All y values should be finite"
    assert y.std() > 0, f"Length {length}: Should have variation"

    # Test x coordinate bounds
    assert x.min() >= 0, f"Length {length}: X coordinates should be >= 0"
    assert x.max() <= 1.001, f"Length {length}: X coordinates should be <= 1"

    # Test that longer curves have more unique values
    unique_values = len(np.unique(np.round(y, 6)))
    assert unique_values > length // 50, f"Length {length}: Should have sufficient variation"
