#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Test Koch Curve and Snowflake Generation
========================================

Test cases for generating Koch curves and Koch snowflakes using fracDimPy.
The Koch curve is one of the most famous fractal curves, generated by
recursively replacing line segments with specific shapes. The Koch snowflake is a
closed figure formed by three Koch curves.

Theoretical Background:
- Fractal dimension of Koch curve: D = log(4)/log(3) ~= 1.2619
- Each iteration replaces one line segment with 4 segments, length becomes 1/3 of original
- Koch snowflake is formed by 3 Koch curves, with infinite perimeter and finite area
"""

import numpy as np
import os
import pytest


def test_koch_curve_basic_generation():
    """Test basic Koch curve generation functionality."""
    from fracDimPy import generate_koch_curve

    # Test basic generation
    level = 3
    size = 512

    points, image = generate_koch_curve(level=level, size=size)

    # Test basic properties
    assert len(points) > 0, "Should generate points"
    assert points.shape[1] == 2, "Points should be 2D coordinates"
    assert image.shape == (size, size), f"Image should be {size}x{size}"
    assert image.dtype in [np.float64, np.float32, np.uint8, np.bool_], "Valid image dtype expected"

    # Test image properties
    assert np.any(image > 0), "Image should contain non-zero values"
    assert np.any(image < np.max(image)), "Image should have variation"


def test_koch_curve_different_levels():
    """Test Koch curve generation at different iteration levels."""
    from fracDimPy import generate_koch_curve

    size = 256
    levels = [0, 1, 2, 3, 4]

    point_counts = []
    for level in levels:
        points, image = generate_koch_curve(level=level, size=size)

        # Test basic properties
        assert len(points) > 0, f"Level {level}: Should generate points"
        assert image.shape == (size, size), f"Level {level}: Incorrect image size"

        point_counts.append(len(points))

        # Test monotonic increase in point count with level
        if level > 0:
            assert len(points) > point_counts[level-1], \
                f"Level {level}: Should have more points than level {level-1}"

    # Test that higher levels generate more points (exponential growth)
    for i in range(1, len(levels)):
        assert point_counts[i] > point_counts[i-1], \
            f"Point count should increase with level (level {i} vs {i-1})"


def test_koch_snowflake_basic_generation():
    """Test basic Koch snowflake generation functionality."""
    from fracDimPy import generate_koch_snowflake

    # Test basic generation
    level = 3
    size = 512

    snowflake = generate_koch_snowflake(level=level, size=size)

    # Test basic properties
    assert snowflake.shape == (size, size), f"Image should be {size}x{size}"
    assert np.any(snowflake > 0), "Snowflake should contain non-zero values"
    assert np.any(snowflake < np.max(snowflake)), "Should have variation in values"

    # Test that snowflake is symmetric (has some symmetry properties)
    # Koch snowflake should have 6-fold symmetry
    center_x, center_y = size // 2, size // 2

    # Check that it's not just a line or single point
    non_zero_coords = np.where(snowflake > 0)
    assert len(non_zero_coords[0]) > 10, "Should have substantial non-zero area"
    assert len(non_zero_coords[1]) > 10, "Should have substantial non-zero area"


def test_koch_snowflake_different_levels():
    """Test Koch snowflake generation at different iteration levels."""
    from fracDimPy import generate_koch_snowflake

    size = 256
    levels = [0, 1, 2, 3]

    non_zero_counts = []
    for level in levels:
        snowflake = generate_koch_snowflake(level=level, size=size)

        # Test basic properties
        assert snowflake.shape == (size, size), f"Level {level}: Incorrect image size"

        non_zero_count = np.sum(snowflake > 0)
        non_zero_counts.append(non_zero_count)

        # Should have some non-zero pixels for all levels
        assert non_zero_count > 0, f"Level {level}: Should have non-zero pixels"

    # Test that higher levels generally have more detail (not necessarily more pixels)
    # but the complexity should increase
    for i in range(1, len(levels)):
        # Allow for some variation in pixel count but check general trend
        assert abs(non_zero_counts[i] - non_zero_counts[i-1]) < size * size, \
            f"Pixel count should not vary dramatically between levels {i} and {i-1}"


def test_koch_properties():
    """Test theoretical properties of Koch curves and snowflakes."""
    # Test theoretical fractal dimension
    theoretical_dim = np.log(4) / np.log(3)
    assert 1.26 < theoretical_dim < 1.27, "Theoretical dimension should be ~1.2619"

    # Test that Koch curve has self-similarity (approximate)
    # The total length should increase by factor 4/3 each iteration
    from fracDimPy import generate_koch_curve

    size = 256
    levels = [1, 2, 3]

    point_counts = []
    for level in levels:
        points, _ = generate_koch_curve(level=level, size=size)
        point_counts.append(len(points))

    # Test that point count grows roughly as 4^level
    for i, level in enumerate(levels):
        expected_min = 3 * (4 ** (level - 1)) if level > 0 else 3
        assert point_counts[i] >= expected_min * 0.8, \
            f"Level {level}: Point count {point_counts[i]} should be at least {expected_min * 0.8}"


def test_koch_edge_cases():
    """Test edge cases for Koch generation."""
    from fracDimPy import generate_koch_curve, generate_koch_snowflake

    # Test with small size
    size = 64
    points, image = generate_koch_curve(level=2, size=size)
    assert image.shape == (size, size), "Small size should work"

    snowflake = generate_koch_snowflake(level=1, size=size)
    assert snowflake.shape == (size, size), "Small size snowflake should work"

    # Test with level 0 (should be basic triangle for snowflake, line for curve)
    points_0, image_0 = generate_koch_curve(level=0, size=256)
    assert len(points_0) >= 2, "Level 0 curve should have at least 2 points"

    snowflake_0 = generate_koch_snowflake(level=0, size=256)
    assert np.sum(snowflake_0 > 0) > 0, "Level 0 snowflake should have non-zero pixels"


@pytest.mark.parametrize("level", [1, 2, 3])
def test_koch_curve_level_parameter(level):
    """Test Koch curve generation with different level parameters."""
    from fracDimPy import generate_koch_curve

    size = 256
    points, image = generate_koch_curve(level=level, size=size)

    assert len(points) > 0, f"Level {level}: Should generate points"
    assert image.shape == (size, size), f"Level {level}: Correct image size"
    assert np.all(np.isfinite(points)), f"Level {level}: All points should be finite"


@pytest.mark.parametrize("level", [1, 2, 3])
def test_koch_snowflake_level_parameter(level):
    """Test Koch snowflake generation with different level parameters."""
    from fracDimPy import generate_koch_snowflake

    size = 256
    snowflake = generate_koch_snowflake(level=level, size=size)

    assert snowflake.shape == (size, size), f"Level {level}: Correct image size"
    assert np.sum(snowflake > 0) > 0, f"Level {level}: Should have non-zero pixels"
    assert np.all(np.isfinite(snowflake)), f"Level {level}: All values should be finite"

