#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Takagi Surface Generation Example
==================================

This example demonstrates how to generate Takagi surfaces using fracDimPy.
The Takagi surface is a two-dimensional generalization of the Takagi curve,
a continuous but nowhere differentiable fractal surface generated by superimposing
waves of different scales, useful for simulating rough surfaces.

Main Features:
- Generate Takagi surfaces with different fractal dimensions
- Visualize in both 3D surface and 2D heatmap forms
- Display the effect of fractal dimension on surface roughness
- Statistics on surface height distribution characteristics

Theoretical Background:
- Fractal dimension of Takagi surface: D ∈ (2, 3)
- Larger D indicates rougher surfaces with greater fluctuations
- Formed by iteratively superimposing waves with different amplitudes and frequencies
- Parameter b controls surface fluctuation degree, b = 2^D / 8
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Takagi Surface Generation Example")
    print("="*60)
    
    from fracDimPy import generate_takagi_surface
    
    # Generate Takagi surfaces
    print("\n1. Generating Takagi surfaces...")
    dimensions = [2.1, 2.5, 2.9]  # Different fractal dimensions
    level = 15                     # Iteration level
    size = 256                     # Surface size
    
    fig = plt.figure(figsize=(15, 10))
    
    for idx, dimension in enumerate(dimensions):
        surface = generate_takagi_surface(dimension=dimension, level=level, size=size)
        
        b = 2 ** dimension / 8  # Calculate parameter b
        print(f"   Fractal dimension D={dimension}: Surface size {size}x{size}, parameter b={b:.4f}")
        print(f"   Value range: {surface.min():.4f} ~ {surface.max():.4f}")
        print(f"   Standard deviation: {surface.std():.4f}")
        
        # 3D surface view
        ax1 = fig.add_subplot(2, 3, idx+1, projection='3d')
        
        # Create coordinate grid
        x = np.linspace(0, 1, size)
        y = np.linspace(0, 1, size)
        X, Y = np.meshgrid(x, y)
        
        # Downsample to improve rendering speed
        step = max(1, size // 50)
        ax1.plot_surface(X[::step, ::step], Y[::step, ::step], 
                        surface[::step, ::step], cmap='terrain', 
                        linewidth=0, antialiased=True)
        
        ax1.set_title(f'Takagi Surface 3D View\n(D={dimension}, b={b:.3f})')
        ax1.set_xlabel('X Coordinate')
        ax1.set_ylabel('Y Coordinate')
        ax1.set_zlabel('Height Value')
        ax1.view_init(elev=30, azim=45)
        
        # 2D heatmap view
        ax2 = fig.add_subplot(2, 3, idx+4)
        im = ax2.imshow(surface, cmap='terrain', origin='lower', 
                       extent=[0, 1, 0, 1], aspect='auto')
        ax2.set_title(f'Takagi Surface 2D View\n(Std Dev={surface.std():.4f})')
        ax2.set_xlabel('X Coordinate')
        ax2.set_ylabel('Y Coordinate')
        plt.colorbar(im, ax=ax2, fraction=0.046, pad=0.04, label='Height Value')
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(current_dir, "result_takagi_surface.png")
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n2. Visualization result saved: {output_file}")
    plt.show()
    
    print("\n" + "="*60)
    print("Theoretical Knowledge Supplement")
    print("="*60)
    print("   Takagi surface is a two-dimensional generalization of Takagi curve")
    print("   Fractal dimension D formula: D = log(8*b) / log(2), where b = 2^D / 8")
    print("   Fractal dimension range: D ∈ (2, 3)")
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()
