#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Koch Curve and Snowflake Generation Example
===========================================

This example demonstrates how to generate Koch curves and Koch snowflakes using
fracDimPy. The Koch curve is one of the most famous fractal curves, generated by
recursively replacing line segments with specific shapes. The Koch snowflake is a
closed figure formed by three Koch curves.

Main Features:
- Generate Koch curves at different levels
- Generate Koch snowflakes at different levels
- Visualize the step-by-step construction process of fractals
- Display theoretical fractal dimension

Theoretical Background:
- Fractal dimension of Koch curve: D = log(4)/log(3) ≈ 1.2619
- Each iteration replaces one line segment with 4 segments, length becomes 1/3 of original
- Koch snowflake is formed by 3 Koch curves, with infinite perimeter and finite area
"""

import numpy as np
import os
import matplotlib.pyplot as plt
# Try to use scienceplots style if available
try:
    import scienceplots
    plt.style.use(['science','no-latex'])
except ImportError:
    pass
# Set font family: Times New Roman for English, Microsoft YaHei for Chinese
plt.rcParams['font.family'] = ['Times New Roman', 'Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display issue

def main():
    print("="*60)
    print("Koch Curve and Snowflake Generation Example")
    print("="*60)
    
    from fracDimPy import generate_koch_curve, generate_koch_snowflake
    
    # 1. Generate Koch curves
    print("\n1. Generating Koch curves...")
    levels_curve = [1, 3, 5]  # Different iteration levels
    size = 512                # Image size
    
    fig1, axes1 = plt.subplots(1, len(levels_curve), figsize=(15, 5))
    
    for idx, level in enumerate(levels_curve):
        points, image = generate_koch_curve(level=level, size=size)
        
        print(f"   Level={level}: Generated {len(points)} points")
        
        # Display Koch curve
        axes1[idx].imshow(image, cmap='binary', origin='upper')
        axes1[idx].set_title(f'Koch Curve\n(Iteration Level={level})')
        axes1[idx].axis('off')
        
        # Add theoretical fractal dimension annotation
        D_theoretical = np.log(4) / np.log(3)
        axes1[idx].text(0.5, -0.05, 
                       f'Theoretical Fractal Dimension: D ≈ {D_theoretical:.4f}',
                       transform=axes1[idx].transAxes,
                       ha='center', va='top',
                       fontsize=9,
                       bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.7))
    
    plt.tight_layout()
    current_dir = os.path.dirname(os.path.abspath(__file__))
    output_file1 = os.path.join(current_dir, "result_koch_curve.png")
    plt.savefig(output_file1, dpi=300, bbox_inches='tight')
    print(f"\n2. Koch curve image saved: {output_file1}")
    
    # 2. Generate Koch snowflakes
    print("\n3. Generating Koch snowflakes...")
    levels_snow = [1, 3, 5]  # Different iteration levels
    
    fig2, axes2 = plt.subplots(1, len(levels_snow), figsize=(15, 5))
    
    for idx, level in enumerate(levels_snow):
        snowflake = generate_koch_snowflake(level=level, size=size)
        
        print(f"   Level={level}: Image size {size}x{size}")
        
        # Display Koch snowflake
        axes2[idx].imshow(snowflake, cmap='binary', origin='upper')
        axes2[idx].set_title(f'Koch Snowflake\n(Iteration Level={level})')
        axes2[idx].axis('off')
        
        # Add theoretical fractal dimension annotation
        D_theoretical = np.log(4) / np.log(3)
        axes2[idx].text(0.5, -0.05, 
                       f'Theoretical Fractal Dimension: D ≈ {D_theoretical:.4f}',
                       transform=axes2[idx].transAxes,
                       ha='center', va='top',
                       fontsize=9,
                       bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))
    
    plt.tight_layout()
    output_file2 = os.path.join(current_dir, "result_koch_snowflake.png")
    plt.savefig(output_file2, dpi=300, bbox_inches='tight')
    print(f"\n4. Koch snowflake image saved: {output_file2}")
    
    plt.show()
    
    print("\n" + "="*60)
    print("Theoretical Knowledge Supplement")
    print("="*60)
    print("   Koch curve is a classic fractal curve")
    print("   Koch snowflake is formed by 3 Koch curves, creating a closed figure")
    print(f"   Fractal dimension: D = log(4)/log(3) ≈ {np.log(4)/np.log(3):.4f}")
    print("   Characteristics: Infinite perimeter, finite area")
    print("\nExample execution completed!")


if __name__ == '__main__':
    main()

